"""Generate a lightweight business-facing data catalog for governance."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROC_DIR = PROJECT_ROOT / "data" / "processed"
OUT_TABLES_DIR = PROJECT_ROOT / "outputs" / "tables"

DATASETS = [
    ("raw", "customers", RAW_DIR / "customers.csv"),
    ("raw", "transactions", RAW_DIR / "transactions.csv"),
    ("raw", "marketing_spend", RAW_DIR / "marketing_spend.csv"),
    ("processed", "customer_metrics", PROC_DIR / "customer_metrics.csv"),
    ("processed", "cohort_table", PROC_DIR / "cohort_table.csv"),
    ("processed", "unit_economics", PROC_DIR / "unit_economics.csv"),
    ("output", "monthly_revenue_health", OUT_TABLES_DIR / "monthly_revenue_health.csv"),
    ("output", "main_analysis_findings", OUT_TABLES_DIR / "main_analysis_findings.csv"),
]

FIELD_DEFINITIONS: dict[str, tuple[str, str]] = {
    # Identifiers
    "customer_id": ("Unique customer identifier.", "Join key across customer and transaction views."),
    "transaction_id": ("Unique transaction identifier.", "Duplicate control on transactional facts."),
    # Dimensions
    "segment": ("Customer segment (SMB, Mid-Market, Enterprise).", "Cross-cut for margin and retention diagnostics."),
    "region": ("Customer region (EMEA, AMER, APAC).", "Geographic mix and regional profitability."),
    "acquisition_channel": ("Channel attributed to customer acquisition.", "Unit economics and budget allocation."),
    "product_type": ("Product line for the transaction.", "Product mix and profitability analysis."),
    # Temporal
    "signup_date": ("Date the customer first signed up.", "Cohort assignment."),
    "transaction_date": ("Date the transaction occurred.", "Time-series aggregation."),
    "date": ("Calendar date.", "Time-series aggregation."),
    "cohort_month": ("Signup month used as cohort key.", "Cohort retention analysis."),
    "activity_month": ("Month in which the cohort generated revenue.", "Retention curve x-axis."),
    "month": ("Calendar month, first-of-month timestamp.", "Monthly aggregation."),
    "first_transaction_date": ("First observed transaction for the customer.", "Customer lifetime window start."),
    "last_transaction_date": ("Last observed transaction for the customer.", "Customer lifetime window end."),
    # Money / counts
    "revenue": ("Gross revenue booked on the transaction.", "Top-line growth and mix."),
    "cost": ("Direct delivery cost linked to the transaction.", "Contribution margin and unit economics."),
    "spend": ("Marketing spend recorded for the day and channel.", "CAC and channel ROI."),
    "total_revenue": ("Sum of revenue over the grouping window.", "Top-line measurement."),
    "total_cost": ("Sum of direct cost over the grouping window.", "Margin measurement."),
    "total_spend": ("Sum of marketing spend over the grouping window.", "CAC denominator input."),
    "contribution_margin": ("Revenue minus direct cost.", "Primary profitability measure."),
    "contribution_margin_pct": ("Contribution margin as share of revenue.", "Margin quality signal."),
    "contribution_margin_growth_mom": ("Month-over-month change in contribution margin.", "Margin trend monitoring."),
    "revenue_growth_mom": ("Month-over-month change in total revenue.", "Top-line momentum."),
    "cost_growth_mom": ("Month-over-month change in total cost.", "Cost trajectory."),
    "transaction_count": ("Number of transactions in the grouping.", "Volume measure."),
    "active_customers": ("Distinct customers active in the period.", "Engagement measure."),
    "customers_acquired": ("Customers whose signup falls in the period.", "CAC denominator."),
    "customers_active": ("Distinct active customers in the cohort/period.", "Retention denominator."),
    "cohort_revenue": ("Revenue generated by the cohort in the activity month.", "Cohort retention numerator."),
    "average_revenue_per_active_customer": ("Cohort revenue divided by active customers.", "Per-user revenue trajectory."),
    "avg_revenue_per_transaction": ("Mean transaction revenue for the customer.", "Ticket-size diagnostics."),
    "revenue_per_day": ("Total revenue divided by observed lifetime days.", "Per-day intensity."),
    "lifetime_days": ("Days between first and last observed transaction.", "Observation window size."),
    # Unit economics
    "CAC": ("Channel marketing spend divided by customers acquired.", "Channel efficiency."),
    "LTV_to_CAC": ("Average observed LTV divided by CAC.", "Scaling guardrail."),
    "approximate_payback_period": ("Months of margin needed to recover CAC.", "Capital efficiency proxy."),
    "average_LTV": ("Mean contribution margin per acquired customer.", "Value side of LTV/CAC."),
    "median_LTV": ("Median contribution margin per acquired customer.", "Skew-robust value check."),
    # Findings table
    "section": ("Analysis section the finding belongs to.", "Narrative grouping."),
    "question": ("Business question the finding answers.", "Decision framing."),
    "result": ("Quantitative or qualitative result.", "Headline figure."),
    "metrics_used": ("Metrics referenced to produce the result.", "Auditability."),
    "business_interpretation": ("Plain-English interpretation of the result.", "Stakeholder communication."),
    "caveats": ("Known limitations or assumptions.", "Honest framing of confidence."),
}

LAYER_OWNER = {
    "raw": "Data Engineering",
    "processed": "Analytics Engineering",
    "output": "Analytics Lead",
}


def _infer_role(column: str, dtype: str) -> str:
    c = column.lower()
    if c.endswith("_id") or c in {"cid"}:
        return "identifier"
    if "date" in c or "month" in c:
        return "temporal"
    if c.startswith("is_") or c.startswith("has_"):
        return "boolean"
    if "float" in dtype or "int" in dtype:
        return "metric"
    return "dimension"


def build_data_catalog() -> pd.DataFrame:
    rows: list[dict[str, str]] = []
    for layer, dataset, path in DATASETS:
        if not path.exists():
            continue
        frame = pd.read_csv(path, nrows=200)
        for col, dtype in frame.dtypes.items():
            definition, business_use = FIELD_DEFINITIONS.get(col, ("", ""))
            rows.append(
                {
                    "layer": layer,
                    "dataset": dataset,
                    "column": col,
                    "dtype": str(dtype),
                    "role": _infer_role(col, str(dtype)),
                    "owner": LAYER_OWNER[layer],
                    "definition": definition,
                    "business_use": business_use,
                }
            )
    return pd.DataFrame(rows).sort_values(
        ["layer", "dataset", "column"], ignore_index=True
    )


def write_data_catalog_artifacts() -> None:
    OUT_TABLES_DIR.mkdir(parents=True, exist_ok=True)

    catalog = build_data_catalog()
    catalog.to_csv(OUT_TABLES_DIR / "data_catalog.csv", index=False)
